// <auto-generated />
using Computer_Store_Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Computer_Store_Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230109075634_version_0.5")]
    partial class version_05
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Computer_Store_Api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            Name = "Admin",
                            PassWord = "admin",
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Computer_Store_Api.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Computer_Store_Api.Models.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cart_details");
                });

            modelBuilder.Entity("Computer_Store_Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("order");
                });

            modelBuilder.Entity("Computer_Store_Api.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("order_details");
                });

            modelBuilder.Entity("Computer_Store_Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Drive")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Monitor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VGA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPU = "Intel Core i5 11400H",
                            Category = "Computer",
                            Description = "l",
                            Drive = "512GB SSD",
                            Image = "/product/imgHomepage/250-21734-laptop-gigabyte-gaming-g5-md-51s1123so.jpg",
                            Monitor = "15.6 inch FHD 144Hz",
                            Name = "Laptop Gigabyte Gaming G5 MD 51S1123SO ( i5-11400H/ 16GB/ 512GB SSD/ 15.6\" FHD/RTX3050Ti 4Gb/ Win11)",
                            Price = 0.0,
                            ProductType = "Lap-top",
                            RAM = "16gb",
                            VGA = "NVIDIA RTX3050Ti 4G"
                        },
                        new
                        {
                            Id = 2,
                            CPU = "Core i5 11400H (2.6 Ghz Up to 4.4 Ghz, 12MB)",
                            Category = "Computer",
                            Description = "l",
                            Drive = "512GB SSD / có thể Nâng cấp 1 ổ Sata 2.5'",
                            Image = "/product/imgHomepage/250-21725-laptop-gigabyte-gaming-g5-md-51s1123so.jpg",
                            Monitor = "15.6 Inch Full HD, 100% srgb",
                            Name = "Laptop Gigabyte Gaming G5 MD 51S1123SO ( i5-11400H/ 16GB/ 512GB SSD/ 15.6' FHD/RTX3050Ti 4Gb/ Win11)",
                            Price = 0.0,
                            ProductType = "Lap-top",
                            RAM = "16GB 3200Mhz, 2 Khe, up to 32GB",
                            VGA = "NVIDIA GeForce RTX 3050 4GB GDDR6"
                        },
                        new
                        {
                            Id = 3,
                            CPU = "AMD Ryzen™ 3-5300U (2.6GHz upto 3.8GHz, 4MB)",
                            Category = "Computer",
                            Description = "l",
                            Drive = "256GB PCIe NVMe",
                            Image = "/product/imgHomepage/250-21615-hp-14s.jpg",
                            Monitor = "14 inch HD (1366 x 768), micro-edge, BrightView, 250 nits, 45% NTSC",
                            Name = "Laptop HP 14s-fq1080AU 4K0Z7PA (Ryzen 3-5300U/ 4GB / 256GB SSD/ 14' HD/ AMD Radeon/ Win10/ Silver/ 1 Yr)",
                            Price = 0.0,
                            ProductType = "Lap-top",
                            RAM = "4GB (1x4GB) DDR4-3200Mhz (2 khe)",
                            VGA = "Radeon Vega Graphics"
                        },
                        new
                        {
                            Id = 4,
                            CPU = "Intel Core I3-1115G4",
                            Category = "Computer",
                            Description = "l",
                            Drive = "256GB SSD",
                            Image = "/product/imgHomepage/250-22706-msi-14.jpg",
                            Monitor = "14 inch FHD 60 Hz",
                            Name = "Laptop MSI Modern 14 B11MOU-1027VN (I3-1115G4/ 8GB RAM / 256GB SSD/ 14' FHD, 60Hz/ VGA ON/ Win11/ Grey/ 1 Yr)",
                            Price = 0.0,
                            ProductType = "Lap-top",
                            RAM = "8GB",
                            VGA = "Intel UHD Graphics"
                        },
                        new
                        {
                            Id = 5,
                            CPU = "Intel Core i9-11900K",
                            Category = "Item",
                            Description = "l",
                            Drive = " ",
                            Image = "/product/imgHomepage/18678-intel-core-i9-11900k.jpg",
                            Monitor = " ",
                            Name = "CPU Intel Core i9-11900K (8 Nhân 16 Luồng | 3.50 GHz Turbo 5.3GHz | 16M Cache | 125W)",
                            Price = 0.0,
                            ProductType = "CPU",
                            RAM = " ",
                            VGA = " "
                        },
                        new
                        {
                            Id = 6,
                            CPU = "Intel Core i9-11900KF",
                            Category = "Item",
                            Description = "l",
                            Drive = " ",
                            Image = "/product/imgHomepage/18676-cpunc8.jpg",
                            Monitor = " ",
                            Name = "CPU Intel Core i9-11900KF (8 Nhân 16 Luồng | Turbo 5.3GHz | 16M Cache | 125W)",
                            Price = 0.0,
                            ProductType = "CPU",
                            RAM = " ",
                            VGA = " "
                        },
                        new
                        {
                            Id = 7,
                            CPU = " ",
                            Category = "Item",
                            Description = "l",
                            Drive = " ",
                            Image = "/product/imgHomepage/23423-m--n-h--nh-hkc-m24g1-24-0-inch-full-hd-144hz-4.jpg",
                            Monitor = "HKC M24G1 24.0 inch",
                            Name = "Màn hình HKC M24G1 24.0 inch Full HD 144HZ - Cong",
                            Price = 0.0,
                            ProductType = "Screen",
                            RAM = " ",
                            VGA = " "
                        },
                        new
                        {
                            Id = 8,
                            CPU = " ",
                            Category = "Item",
                            Description = "l",
                            Drive = " ",
                            Image = "/product/imgHomepage/18979-vganc2.jpg",
                            Monitor = " ",
                            Name = "Card Màn Hình ZOTAC GAMING GeForce GTX 1650 SUPER Twin Fan 4G GDDR6",
                            Price = 0.0,
                            ProductType = "Card",
                            RAM = " ",
                            VGA = "ZOTAC GAMING GeForce GTX 1650 SUPER"
                        });
                });

            modelBuilder.Entity("Computer_Store_Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "HN",
                            Name = "test1",
                            PassWord = "test1",
                            PhoneNumber = "1",
                            UserName = "test1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "HN",
                            Name = "test2",
                            PassWord = "test2",
                            PhoneNumber = "1",
                            UserName = "test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
